export function createGameGlobals() {
    return {
        arrowStartSquare: null,
        currentHoverSquare: null,
        previewArrow: null,
        previewHighlight: null,
        isRightClickDragging: false,
        savedArrows: new Set(),
        ratingInterval: null,
        MOVE_IN_PROGRESS: false,
        HALF_MOVE_THRESHOLD: 18,
        ENGINE_RUNNING: false,
        CURRENTLY_HIGHLIGHTED_SQUARE: null,
        DRAG_START_SQUARE: null,
        userInfo: null,
        gameState: {
            playing: false,
            position: null,
            userColor: null,
            colorToMove: null,
            premove: null,
            isRated: false,
            userRating: null,
            halfMoveNumber: 0,
            moveHistorySAN: [],
            moveHistoryUCI: [],
            fenHistory: [],
            evaluations: [],
        },
        legalMoves: [],
        legalSans: [],
        fenResults: [],
        moveIsMate: [],
        initialEval: 0,
        currentBrowsePosition: -1,
        lastDrawnPosition: -1,
    };
}
